### ISSUE TITLE
[ryukyu] flickering horizontal line

### ISSUE THREAD

**Issue by atrac17** [JTFPGA/jts16#40]
## **RyuKyu (Rev A, Japan) (FD1094 317-5023A)**

After coin up and starting the game, the intro has a misplaced line in the water and scroll issues. Screen shot is for starting reference. You cannot capture this with prt sc.
 
<details>

<summary><b>Click to view screenshots</b></summary>

<blockquote>

![20210721_082158-screen](https://user-images.githubusercontent.com/32810066/126488332-98cbc02c-7b00-4932-821f-cf5b723f32e1.png)
![20210721_082159-screen](https://user-images.githubusercontent.com/32810066/126488334-295344a9-3728-404a-bb27-c0aec847f3fe.png)
![20210721_082202-screen](https://user-images.githubusercontent.com/32810066/126488336-fd378321-6d9c-4853-9d83-d3598cb42676.png)
![20210721_082204-screen](https://user-images.githubusercontent.com/32810066/126488339-ed26b2bb-0461-4631-81a0-3388381e2bdb.png)
![20210721_082207-screen](https://user-images.githubusercontent.com/32810066/126488344-61265377-bcd9-4ea7-affb-d0ce7c142c55.png)
![20210721_082208-screen](https://user-images.githubusercontent.com/32810066/126488345-03c58188-6d39-47da-84e6-9df5bbb57a87.png)
![20210721_082214-screen](https://user-images.githubusercontent.com/32810066/126488346-db1a34fd-f861-40f5-9d70-f3ef69487635.png)

</blockquote>

</details>

<details>

<summary><b>Click to download nvm file</b></summary>

<blockquote>

[RyuKyu (Rev A, Japan) (FD1094 317-5023A).zip](https://github.com/JTFPGA/jts16/files/6855664/RyuKyu.Rev.A.Japan.FD1094.317-5023A.zip)

</blockquote>

</details>

**Comment by jotego** [comment]
This still occurs on commit 0f4872f9. It can also be seen on scroll B on Cotton title screen. Moving this issue [here](https://github.com/jotego/jtcores/issues/299).
