### ISSUE TITLE
[sonicboom] graphic issue in level transitions

### ISSUE THREAD

**Issue by ItsAtomico** [JTFPGA/jts16#56]
Explosions and other leftover graphics from the previous boss fight remain on screen during the stage bonus tally scene:

https://user-images.githubusercontent.com/69975383/127926535-88bc3186-173a-49e7-927c-793e90a41ab5.mp4

MAME: 

https://user-images.githubusercontent.com/69975383/127926805-c28970d4-a407-4df1-b835-568db9e61b4f.mp4

Using... the first S16 with the H scale option..? "About" screen didn't have a commit date.

**Comment by florgana** [comment]
graphic issue in level transitions (explosions and other leftover graphics ) is fixed.
