### ISSUE TITLE
[eswat] [eswatu] [eswatj] Stage 9 Monster Truck

### ISSUE THREAD

**Issue by ItsAtomico** [JTFPGA/jts16#71]
https://www.youtube.com/watch?v=FgCJNMPyQ2Q
Monster truck  in stage 9 glitches out when it first appears on screen (it should keep poking in from the side throughout the stage, dropping enemies onto you).

![vlcsnap-2021-11-09-10h28m39s100](https://user-images.githubusercontent.com/69975383/140932636-3e43e5a8-481a-4963-a2d4-0a508304d209.png)
Instead it disappears completely and doesn't show up for the actual boss fight. You're stuck at the end of the level.

![vlcsnap-2021-11-09-10h30m10s546](https://user-images.githubusercontent.com/69975383/140932788-f6e5fa41-588b-4ff2-8ee3-c5d98f414f82.png)

Here's where it gets even weirder: in `eswatj` I managed to wait out the timer , continue then wait some more and the truck appeared.
![140933071-cfbd6a3b-74cb-4208-82c8-a688c977b8bc](https://user-images.githubusercontent.com/69975383/141402983-8bfa4acd-cfc0-4c17-a4df-595c5eede5bd.png)
Sunken truck can still be damaged and destroyed.  Game moves on afterwards.

No such luck in `eswat` or `eswatu`. Truck doesn't appear even after several countouts .

Using `v8ab1e80`
`eswatj1` is the only set working properly. Video here: https://www.youtube.com/watch?v=99N-ZtSEVt8

**Comment by jotego** [comment]
Tracked on https://github.com/jotego/jtcores/issues/172
